services:

  database:
    image: database:1.0.0
    container_name: ${DATABASE_HOST}
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - database-v:/data/db

volumes:
 database-v:
    name: "database-v"
